defaults:
  - fno.yaml

output_dir: experiments/fno_full_on_holdout/bathymetry_trench

data:
  test_path: data/processed_strict_holdout/hydrostatic/bathymetry_holdout_trench/test_heldout
  batch_size: 64

eval:
  dataset_path: data/processed_strict_holdout/hydrostatic/bathymetry_holdout_trench/test_heldout
  output_dir: experiments/fno_full_on_holdout/bathymetry_trench/eval_heldout
